spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/gpro_events
    username: erijmahjoub
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: change-me-en-une-longue-chaine-aleatoire-min-32-caracteres
  expiration-ms: 86400000 # 24h